# Generated by Django 3.2.19 on 2023-05-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola_app', '0002_auto_20230527_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
